const categories = ["Groceries & Snacks","Toiletries & Personal Care","Household Basics","Health & Comfort","Functional Recovery","Work & Productivity","Electronics & Accessories","Streaming & Subscriptions","Dining / Coffee / Convenience","Emergency Cushion"];
const defaultBudgets = {
  comfortable: {"Groceries & Snacks":150,"Toiletries & Personal Care":40,"Household Basics":35,"Health & Comfort":50,"Functional Recovery":75,"Work & Productivity":50,"Electronics & Accessories":50,"Streaming & Subscriptions":75,"Dining / Coffee / Convenience":40,"Emergency Cushion":100},
  functional: {"Groceries & Snacks":150,"Toiletries & Personal Care":50,"Household Basics":45,"Health & Comfort":75,"Functional Recovery":150,"Work & Productivity":100,"Electronics & Accessories":75,"Streaming & Subscriptions":75,"Dining / Coffee / Convenience":50,"Emergency Cushion":100}
};
const knownSeed = {id:crypto.randomUUID(), amount:27.54, category:"Groceries & Snacks", scenario:"comfortable", reviewLabel:"green", purchaseDate:"", note:"GS-01 Basic groceries. Known imported update: C3:R2 = $27.54; Comfortable Remaining = $47.46; Groceries category remaining = $122.46.", loggedDate:new Date().toISOString(), outcomeScore:0};
let state = JSON.parse(localStorage.getItem("pscp-state-v01") || "null") || {purchases:[knownSeed], budgets:defaultBudgets, changes:[{purchaseDate:"", loggedDate:new Date().toISOString(), cell:"C3:R2", action:"Seed update", amount:27.54, note:"GS-01 Basic groceries imported into PSCP v0.1."}]};
let budgetMode = "comfortable";
function money(n){return (n<0?"-$":"$")+Math.abs(n).toFixed(2)}
function save(){localStorage.setItem("pscp-state-v01", JSON.stringify(state)); render();}
function actualFor(mode,cat){return state.purchases.filter(p=>(p.scenario===mode||p.scenario==="both")&&p.category===cat).reduce((s,p)=>s+Number(p.amount),0)}
function totals(mode){let budget=0, actual=0; categories.forEach(c=>{budget+=state.budgets[mode][c]||0; actual+=actualFor(mode,c)}); return {budget,actual,remaining:budget-actual}}
function fillSelect(id){const el=document.getElementById(id); categories.forEach(c=>{const o=document.createElement("option");o.value=c;o.textContent=c;el.appendChild(o)})}
fillSelect("category"); fillSelect("helpCategory"); document.getElementById("purchaseDate").valueAsDate = new Date();
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab,.screen").forEach(x=>x.classList.remove("active")); b.classList.add("active"); document.getElementById(b.dataset.screen).classList.add("active")});
document.querySelectorAll(".scenarioToggle").forEach(b=>b.onclick=()=>{budgetMode=b.dataset.mode; document.querySelectorAll(".scenarioToggle").forEach(x=>x.classList.remove("active")); b.classList.add("active"); renderBudget()});
document.getElementById("purchaseForm").onsubmit=e=>{e.preventDefault(); const p={id:crypto.randomUUID(), amount:Number(amount.value), category:category.value, scenario:scenario.value, reviewLabel:reviewLabel.value, purchaseDate:purchaseDate.value, note:note.value.trim(), loggedDate:new Date().toISOString(), outcomeScore:0}; state.purchases.unshift(p); state.changes.unshift({purchaseDate:p.purchaseDate,loggedDate:p.loggedDate,cell:"QuickAdd",action:"Add purchase",amount:p.amount,note:`${p.category} / ${p.scenario}. ${p.note}`}); e.target.reset(); document.getElementById("purchaseDate").valueAsDate = new Date(); save();};
document.getElementById("resetBtn").onclick=()=>{if(confirm("Reset PSCP v0.1 data on this browser?")){localStorage.removeItem("pscp-state-v01"); location.reload();}};
document.getElementById("recommendBtn").onclick=()=>{const idea=document.getElementById("idea").value || "this purchase"; const impact=document.getElementById("impact").value; let label="🟡 Yellow", text="Wait, compare alternatives, and make sure it solves a real problem."; if(["recovery","health","productivity"].includes(impact)){label="🔵 Strategic"; text="Likely worth considering if it improves function, stability, or future earning capacity."} if(impact==="entertainment"){label="🟡 Yellow"; text="Consider only if it clearly improves quality of life and does not crowd out recovery priorities."} recommendation.innerHTML=`<h3>${label}</h3><p><strong>${idea}</strong></p><p>${text}</p>`};
function renderDashboard(){const func=totals("functional"), comfort=totals("comfortable"); document.getElementById("functionalSpend").textContent=money(func.actual); document.getElementById("strategicCount").textContent=state.purchases.filter(p=>p.reviewLabel==="strategic").length; document.getElementById("outcomeNeeded").textContent=state.purchases.filter(p=>p.outcomeScore===0).length; document.getElementById("totalRemaining").textContent=money(comfort.remaining+func.remaining); scenarioSummary.innerHTML=["comfortable","functional"].map(m=>{const t=totals(m);return `<div class="summary-row"><span>${m[0].toUpperCase()+m.slice(1)}</span><strong>${money(t.actual)} spent / ${money(t.remaining)} left</strong></div>`}).join(""); recentPurchases.innerHTML=state.purchases.slice(0,5).map(p=>`<div class="item"><span><span class="pill">${p.reviewLabel}</span><br>${p.category}<br><small>${p.note||"No note"}</small></span><strong>${money(p.amount)}</strong></div>`).join("")||"No purchases yet.";}
function renderBudget(){budgetRows.innerHTML=categories.map(c=>{const b=state.budgets[budgetMode][c]||0, a=actualFor(budgetMode,c), r=b-a; return `<tr><td>${c}</td><td>${money(b)}</td><td>${money(a)}</td><td class="${r<0?'negative':''}">${money(r)}</td></tr>`}).join("");}
function renderChanges(){changeLog.innerHTML=state.changes.map(ch=>`<div class="item"><span><strong>${ch.action}</strong><br><small>${ch.cell} · ${new Date(ch.loggedDate).toLocaleString()}</small><br>${ch.note}</span><strong>${money(ch.amount)}</strong></div>`).join("");}
function render(){renderDashboard(); renderBudget(); renderChanges();}
if("serviceWorker" in navigator){navigator.serviceWorker.register("service-worker.js").catch(()=>{});} render();
